models:
  image: tp33/django
  container_name: models
  external_links:
    - mysql:db
  volumes:
    - ./app/isa:/app/isa
  expose:
    - "8000"
  ports:
    - "8001:8000"
  command: bash -c "python3 /app/isa/manage.py makemigrations && python3 /app/isa/manage.py migrate && python3 /app/isa/manage.py loaddata /app/isa/db2.json && mod_wsgi-express start-server --working-directory /app/isa --reload-on-changes /app/isa/isa/wsgi.py  --log-to-terminal"

experiences:
  image: tp33/django
  container_name: experiences
  links:
    - models:models-api
    - kafka:kafka
    - es:es
  ports:
    - "8002:8000"
  expose:
    - "8000"
  volumes:
    - ./app/experiences:/app
  command: "mod_wsgi-express start-server --reload-on-changes /app/experiences/wsgi.py  --log-to-terminal"


frontend:
  image: tp33/django
  container_name: frontend
  links:
    - experiences:experiences-api
  ports:
    - "8000:8000"
  expose:
    - "8000"
  volumes:
    - ./app/frontend:/app
  command: "mod_wsgi-express start-server --reload-on-changes /app/frontend/wsgi.py --log-to-terminal"

frontend2:
  image: tp33/django
  container_name: frontend2
  links:
    - experiences:experiences-api
  ports:
    - "8003:8000"
  expose:
    - "8000"
  volumes:
    - ./app/frontend:/app
  command: "mod_wsgi-express start-server --reload-on-changes /app/frontend/wsgi.py --log-to-terminal"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      TOPICS: new-listings-topic, pageview-topic
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"
   expose:
      - "9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch:/kafka_script
   command: "python /kafka_script/kafka_script.py --log-to-terminal"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - frontend:frontend
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - frontend:frontend
  volumes:
    - ./selenium:/app
  command: bash -c "pip install selenium==3.141.0 && sleep 30 && python /app/tests.py"

gateway-haproxy:
  image: haproxy
  container_name: gateway-haproxy
  volumes:
  - ./haproxy:/usr/local/etc/haproxy/haproxy.cfg:ro
  links:
   - frontend:frontend
   - frontend2:frontend2
  ports:
   - 8004:8000

jmeter:
  image: hauptmedia/jmeter
  container_name: jmeter
  links:
    - frontend:frontend
  volumes:
    - ./jmeter:/jmeter
  command: bash -c "bin/jmeter -n -t /jmeter/test_1.jmx -l /jmeter/docker_results.log"

spark_batch:
   image: tp33/django
   container_name: spark_batch
   links:
      - kafka:kafka
   volumes:
      - ./spark:/app
   command: "python /app/pageview_script.py --log-to-terminal"

spark-master:
  image: gettyimages/spark
  command: bash -c "chmod +x /tmp/data/run_job.sh && /tmp/data/run_job.sh --log-to-terminal"
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./spark:/tmp/data

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./spark:/tmp/data
