models:
  image: tp33/django
  container_name: models
  external_links:
    - mysql:db
  volumes:
    - ./app/isa:/app/isa
  expose:
    - "8000"
  ports:
    - "8001:8000"
  command: bash -c "python3 /app/isa/manage.py makemigrations && python3 /app/isa/manage.py migrate && python3 /app/isa/manage.py loaddata /app/isa/db2.json && mod_wsgi-express start-server --working-directory /app/isa --reload-on-changes /app/isa/isa/wsgi.py  --log-to-terminal"

experiences:
  image: tp33/django
  container_name: experiences
  links:
    - models:models-api
    - kafka:kafka
    - es:es
  ports:
    - "8002:8000"
  expose:
    - "8000"
  volumes:
    - ./app/experiences:/app
  command: "mod_wsgi-express start-server --reload-on-changes /app/experiences/wsgi.py  --log-to-terminal"


frontend:
  image: tp33/django
  container_name: frontend
  links:
    - experiences:experiences-api
  ports:
    - "8000:8000"
  expose:
    - "8000"
  volumes:
    - ./app/frontend:/app
  command: "mod_wsgi-express start-server --reload-on-changes /app/frontend/wsgi.py --log-to-terminal"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"
   expose:
      - "9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./batch:/kafka_script
   command: "python /kafka_script/kafka_script.py"

selenium-chrome:
  image: selenium/standalone-chrome
  container_name: selenium-chrome
  links:
    - frontend:frontend
  ports:
    - "4444:4444"

selenium-test:
  image: tp33/django
  container_name: selenium-test
  links:
    - selenium-chrome:selenium-chrome
    - frontend:frontend
  volumes:
    - ./selenium:/app
  command: bash -c "pip install selenium==3.141.0 && sleep 30 && python /app/tests.py && tail -f /dev/null"
