models:
  image: tp33/django
  external_links:
    - mysql:db
  volumes:
    - ./app/isa:/app/isa
  ports:
    - "8001:8000"
  command: bash -c "mod_wsgi-express start-server loaddata --working-directory /app/isa --reload-on-changes /app/isa/isa/wsgi.py"
