# Generated by Django 2.1 on 2019-02-17 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('duration', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=500)),
                ('name', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=500)),
                ('name', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField(default=0)),
                ('company', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.Seller'),
        ),
    ]
