# Generated by Django 2.1 on 2019-02-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='Seller',
            new_name='User',
        ),
    ]
