# Generated by Django 2.1 on 2019-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
