# Generated by Django 2.1 on 2019-02-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190217_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='site_title',
            field=models.CharField(default='google.com', max_length=255),
        ),
        migrations.AddField(
            model_name='ad',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
