# Generated by Django 2.1 on 2019-05-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190307_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('Page_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Related_pages', models.CharField(max_length=200)),
            ],
        ),
    ]
