# Generated by Django 2.1 on 2019-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190220_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='site_title',
            field=models.CharField(default='Google', max_length=255),
        ),
    ]
