# Generated by Django 2.1 on 2019-02-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20190217_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.TextField(max_length=100),
        ),
    ]
