# Generated by Django 2.1 on 2019-02-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20190217_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='User',
        ),
    ]
