# Generated by Django 2.1 on 2019-02-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20190219_0711'),
    ]

    operations = [
    ]
